### PR TITLE
Adds lib functions

### PR DESCRIPTION
**Pull request by erp12**

### CODE REVIEW

**Comment by erp12** [comment]
I had to create some custom functions to mirror some Push instructions for which there is no single Clojure core function. Most of these custom functions differ slightly from a Clojure core function except with an explicitly controlled return type. 

Because we don't have support for function overloading, I took the approach of creating unique function names as well as a map of aliases to canonicalize the evolved Clojure functions. I still need to add a few more aliases before this PR is ready for merge.

**Comment by thelmuth** [comment]
Anything you want specific feedback on? Everything I see looks good, as far as I understand it!

**Comment by erp12** [comment]
@thelmuth Do you think the functions I included in the `library` map cover approximately the behavior space as our Push instructions?

**Comment by thelmuth** [comment]
Yup, on first glance. I'd assume some weird ones have snuck in to Clojush over the years, and I know last summer we added some more float instructions that seemed like they were missing (like exponents and roots). But, good enough overlap for first blush.

**Pull request merged**
